/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pharmasist;

/**
 *
 * @author Chamil
 */
public class medlist extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    control_class control;
    public medlist(String medName,String days) {
        initComponents();
        control=control_class.getInstance();
        this.medName.setText(medName);
        this.days.setText(days);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medQty = new javax.swing.JTextField();
        medDone = new javax.swing.JCheckBox();
        medName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        days = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        medDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medDoneActionPerformed(evt);
            }
        });

        medName.setText("name");

        jLabel2.setText("for");

        days.setText("days");

        jLabel4.setText("Days");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(days)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(66, 66, 66)
                .addComponent(medQty, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(medDone)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medDone)
                    .addComponent(medName)
                    .addComponent(jLabel2)
                    .addComponent(days)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void medDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medDoneActionPerformed
        control.updateDatabaseAfterSubmitting(medName.getText(), Integer.parseInt(medQty.getText())) ;
               
        control.getTotalBill(Integer.parseInt(medQty.getText()),medName.getText());
        
        phar1.setPharBill(String.format("%.2f", control.sum));
    }//GEN-LAST:event_medDoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel days;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox medDone;
    private javax.swing.JLabel medName;
    private javax.swing.JTextField medQty;
    // End of variables declaration//GEN-END:variables
}
